let obj = {
  Calories: {
    total: 0,
    Calorie: {
      _id: '620b4606b82695d67f28e193',
      blendId: '1000',
      nutrientName: 'Calorie',
      altName: 'Calories',
      status: 'Review',
      category: {
        _id: '6203a9061c100bd226c13c65',
        blendId: '10',
        categoryName: 'Calories',
      },
      parent: null,
      parentIsCategory: true,
      rank: 1,
      min_measure: '250',
      units: '10',
      unitName: 'kJ',
      children: [],
      total: 0,
    },
  },
  Energy: {
    total: 0,
    Protien: {
      _id: '620b4607b82695d67f28e196',
      blendId: '1001',
      nutrientName: 'Protien',
      altName: null,
      status: 'Active',
      category: {
        _id: '6203a9381c100bd226c13c67',
        blendId: '20',
        categoryName: 'Energy',
      },
      parent: null,
      parentIsCategory: true,
      rank: 1,
      min_measure: '',
      units: '',
      unitName: 'G',
      children: [],
      total: 0,
    },
    Fats: {
      _id: '620b4607b82695d67f28e199',
      blendId: '1002',
      nutrientName: 'Fats',
      altName: null,
      status: 'Active',
      category: {
        _id: '6203a9381c100bd226c13c67',
        blendId: '20',
        categoryName: 'Energy',
      },
      parent: null,
      parentIsCategory: true,
      rank: 2,
      min_measure: '',
      units: '',
      unitName: 'G',
      children: [],
      total: 0,
    },
    Carbohydrates: {
      _id: '620b4608b82695d67f28e19c',
      blendId: '1003',
      nutrientName: 'Carbohydrates',
      altName: null,
      status: 'Active',
      category: {
        _id: '6203a9381c100bd226c13c67',
        blendId: '20',
        categoryName: 'Energy',
      },
      parent: null,
      parentIsCategory: true,
      rank: 3,
      min_measure: '',
      units: '',
      unitName: 'G',
      children: [
        {
          _id: '620b4609b82695d67f28e19f',
          blendId: '1004',
          nutrientName: 'Dietary Fiber',
          altName: null,
          status: 'Active',
          category: {
            _id: '6203a9381c100bd226c13c67',
            blendId: '20',
            categoryName: 'Energy',
          },
          parent: {
            _id: '620b4608b82695d67f28e19c',
            blendId: '1003',
            nutrientName: 'Carbohydrates',
          },
          parentIsCategory: false,
          rank: 1,
          min_measure: '',
          units: '',
          unitName: 'G',
          children: [
            {
              _id: '620b460ab82695d67f28e1a3',
              blendId: '1045',
              nutrientName: 'Fiber, soluble',
              altName: null,
              status: 'Active',
              category: {
                _id: '6203a9381c100bd226c13c67',
                blendId: '20',
                categoryName: 'Energy',
              },
              parent: {
                _id: '620b4609b82695d67f28e19f',
                blendId: '1004',
                nutrientName: 'Dietary Fiber',
              },
              parentIsCategory: false,
              rank: 1,
              min_measure: '',
              units: '',
              unitName: 'G',
            },
            {
              _id: '620b460bb82695d67f28e1a7',
              blendId: '1046',
              nutrientName: 'Fiber, insoluble',
              altName: '',
              status: 'Active',
              category: {
                _id: '6203a9381c100bd226c13c67',
                blendId: '20',
                categoryName: 'Energy',
              },
              parent: {
                _id: '620b4609b82695d67f28e19f',
                blendId: '1004',
                nutrientName: 'Dietary Fiber',
              },
              parentIsCategory: false,
              rank: 2,
              min_measure: '',
              units: '',
              unitName: 'G',
            },
          ],
        },
        {
          _id: '620b460bb82695d67f28e1aa',
          blendId: '1005',
          nutrientName: 'Sugars',
          altName: null,
          status: 'Active',
          category: {
            _id: '6203a9381c100bd226c13c67',
            blendId: '20',
            categoryName: 'Energy',
          },
          parent: {
            _id: '620b4608b82695d67f28e19c',
            blendId: '1003',
            nutrientName: 'Carbohydrates',
          },
          parentIsCategory: true,
          rank: 2,
          min_measure: '',
          units: '',
          unitName: 'G',
          children: [
            {
              _id: '620b460cb82695d67f28e1ae',
              blendId: '1006',
              nutrientName: 'Sucrose',
              altName: null,
              status: 'Active',
              category: {
                _id: '6203a9381c100bd226c13c67',
                blendId: '20',
                categoryName: 'Energy',
              },
              parent: {
                _id: '620b460bb82695d67f28e1aa',
                blendId: '1005',
                nutrientName: 'Sugars',
              },
              parentIsCategory: false,
              rank: 1,
              min_measure: '',
              units: '',
              unitName: 'G',
            },
            {
              _id: '620b460db82695d67f28e1b2',
              blendId: '1007',
              nutrientName: 'Glucose',
              altName: null,
              status: 'Active',
              category: {
                _id: '6203a9381c100bd226c13c67',
                blendId: '20',
                categoryName: 'Energy',
              },
              parent: {
                _id: '620b460bb82695d67f28e1aa',
                blendId: '1005',
                nutrientName: 'Sugars',
              },
              parentIsCategory: false,
              rank: 2,
              min_measure: '',
              units: '',
              unitName: 'G',
            },
            {
              _id: '620b460eb82695d67f28e1b6',
              blendId: '1008',
              nutrientName: 'Fructose',
              altName: null,
              status: 'Active',
              category: {
                _id: '6203a9381c100bd226c13c67',
                blendId: '20',
                categoryName: 'Energy',
              },
              parent: {
                _id: '620b460bb82695d67f28e1aa',
                blendId: '1005',
                nutrientName: 'Sugars',
              },
              parentIsCategory: false,
              rank: 3,
              min_measure: '',
              units: '',
              unitName: 'G',
            },
            {
              _id: '620b460fb82695d67f28e1ba',
              blendId: '1009',
              nutrientName: 'Lactose',
              altName: null,
              status: 'Active',
              category: {
                _id: '6203a9381c100bd226c13c67',
                blendId: '20',
                categoryName: 'Energy',
              },
              parent: {
                _id: '620b460bb82695d67f28e1aa',
                blendId: '1005',
                nutrientName: 'Sugars',
              },
              parentIsCategory: false,
              rank: 4,
              min_measure: '',
              units: '',
              unitName: 'G',
            },
            {
              _id: '620b4610b82695d67f28e1be',
              blendId: '1010',
              nutrientName: 'Maltose',
              altName: null,
              status: 'Active',
              category: {
                _id: '6203a9381c100bd226c13c67',
                blendId: '20',
                categoryName: 'Energy',
              },
              parent: {
                _id: '620b460bb82695d67f28e1aa',
                blendId: '1005',
                nutrientName: 'Sugars',
              },
              parentIsCategory: false,
              rank: 5,
              min_measure: '',
              units: '',
              unitName: 'G',
            },
            {
              _id: '620b4611b82695d67f28e1c2',
              blendId: '1011',
              nutrientName: 'Galactose',
              altName: null,
              status: 'Active',
              category: {
                _id: '6203a9381c100bd226c13c67',
                blendId: '20',
                categoryName: 'Energy',
              },
              parent: {
                _id: '620b460bb82695d67f28e1aa',
                blendId: '1005',
                nutrientName: 'Sugars',
              },
              parentIsCategory: false,
              rank: 6,
              min_measure: '',
              units: '',
              unitName: 'G',
            },
          ],
        },
        {
          _id: '620b4612b82695d67f28e1c6',
          blendId: '1012',
          nutrientName: 'Starch',
          altName: null,
          status: 'Active',
          category: {
            _id: '6203a9381c100bd226c13c67',
            blendId: '20',
            categoryName: 'Energy',
          },
          parent: {
            _id: '620b4608b82695d67f28e19c',
            blendId: '1003',
            nutrientName: 'Carbohydrates',
          },
          parentIsCategory: false,
          rank: 3,
          min_measure: '',
          units: '',
          unitName: 'G',
        },
      ],
      total: 12,
    },
  },
  Vitamins: {
    total: 12,
    data: [
      {
        _id: '620b4613b82695d67f28e1c9',
        blendId: '1013',
        nutrientName: 'Vitamin C',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a96e1c100bd226c13c69',
          blendId: '30',
          categoryName: 'Vitamins',
        },
        parent: null,
        parentIsCategory: true,
        rank: 1,
        min_measure: '',
        units: '',
        unitName: 'MG',
      },
      {
        _id: '620b4613b82695d67f28e1cc',
        blendId: '1014',
        nutrientName: 'Thiamin',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a96e1c100bd226c13c69',
          blendId: '30',
          categoryName: 'Vitamins',
        },
        parent: null,
        parentIsCategory: true,
        rank: 2,
        min_measure: '',
        units: '',
        unitName: 'MG',
      },
      {
        _id: '620b4614b82695d67f28e1cf',
        blendId: '1015',
        nutrientName: 'Riboflavin',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a96e1c100bd226c13c69',
          blendId: '30',
          categoryName: 'Vitamins',
        },
        parent: null,
        parentIsCategory: true,
        rank: 3,
        min_measure: '',
        units: '',
        unitName: 'MG',
      },
      {
        _id: '620b4615b82695d67f28e1d2',
        blendId: '1016',
        nutrientName: 'Niacin',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a96e1c100bd226c13c69',
          blendId: '30',
          categoryName: 'Vitamins',
        },
        parent: null,
        parentIsCategory: true,
        rank: 4,
        min_measure: '',
        units: '',
        unitName: 'MG',
      },
      {
        _id: '620b4615b82695d67f28e1d5',
        blendId: '1017',
        nutrientName: 'Pantothenic acid',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a96e1c100bd226c13c69',
          blendId: '30',
          categoryName: 'Vitamins',
        },
        parent: null,
        parentIsCategory: true,
        rank: 5,
        min_measure: '',
        units: '',
        unitName: 'MG',
      },
      {
        _id: '620b4616b82695d67f28e1d8',
        blendId: '1018',
        nutrientName: 'Vitamin B-6',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a96e1c100bd226c13c69',
          blendId: '30',
          categoryName: 'Vitamins',
        },
        parent: null,
        parentIsCategory: true,
        rank: 6,
        min_measure: '',
        units: '',
        unitName: 'MG',
      },
      {
        _id: '620b4617b82695d67f28e1db',
        blendId: '1019',
        nutrientName: 'Biotin',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a96e1c100bd226c13c69',
          blendId: '30',
          categoryName: 'Vitamins',
        },
        parent: null,
        parentIsCategory: true,
        rank: 7,
        min_measure: '',
        units: '',
        unitName: 'UG',
      },
      {
        _id: '620b4617b82695d67f28e1de',
        blendId: '1020',
        nutrientName: 'Folate',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a96e1c100bd226c13c69',
          blendId: '30',
          categoryName: 'Vitamins',
        },
        parent: null,
        parentIsCategory: true,
        rank: 8,
        min_measure: '',
        units: '',
        unitName: 'UG',
      },
      {
        _id: '620b4618b82695d67f28e1e1',
        blendId: '1021',
        nutrientName: 'Choline',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a96e1c100bd226c13c69',
          blendId: '30',
          categoryName: 'Vitamins',
        },
        parent: null,
        parentIsCategory: true,
        rank: 9,
        min_measure: '',
        units: '',
        unitName: 'MG',
      },
      {
        _id: '620b4619b82695d67f28e1e4',
        blendId: '1022',
        nutrientName: 'Betaine',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a96e1c100bd226c13c69',
          blendId: '30',
          categoryName: 'Vitamins',
        },
        parent: null,
        parentIsCategory: true,
        rank: 10,
        min_measure: '',
        units: '',
        unitName: 'MG',
      },
      {
        _id: '620b4619b82695d67f28e1e7',
        blendId: '1023',
        nutrientName: 'Vitamin B-12',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a96e1c100bd226c13c69',
          blendId: '30',
          categoryName: 'Vitamins',
        },
        parent: null,
        parentIsCategory: true,
        rank: 11,
        min_measure: '',
        units: '',
        unitName: 'UG',
      },
      {
        _id: '620b461ab82695d67f28e1ea',
        blendId: '1024',
        nutrientName: 'Vitamin A',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a96e1c100bd226c13c69',
          blendId: '30',
          categoryName: 'Vitamins',
        },
        parent: null,
        parentIsCategory: true,
        rank: 12,
        min_measure: '',
        units: '',
        unitName: 'UG',
      },
      {
        _id: '620b461ab82695d67f28e1ed',
        blendId: '1025',
        nutrientName: 'Vitamin E',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a96e1c100bd226c13c69',
          blendId: '30',
          categoryName: 'Vitamins',
        },
        parent: null,
        parentIsCategory: true,
        rank: 13,
        min_measure: '',
        units: '',
        unitName: 'MG',
      },
      {
        _id: '620b461bb82695d67f28e1f0',
        blendId: '1026',
        nutrientName: 'Vitamin D',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a96e1c100bd226c13c69',
          blendId: '30',
          categoryName: 'Vitamins',
        },
        parent: null,
        parentIsCategory: true,
        rank: 14,
        min_measure: '',
        units: '',
        unitName: 'IU',
      },
      {
        _id: '620b461cb82695d67f28e1f3',
        blendId: '1027',
        nutrientName: 'Vitamin K',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a96e1c100bd226c13c69',
          blendId: '30',
          categoryName: 'Vitamins',
        },
        parent: null,
        parentIsCategory: true,
        rank: 15,
        min_measure: '',
        units: '',
        unitName: 'UG',
      },
    ],
  },
  Minerals: {
    total: 12,
    data: [
      {
        _id: '620b461cb82695d67f28e1f6',
        blendId: '1028',
        nutrientName: 'Calcium',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a98a1c100bd226c13c6b',
          blendId: '40',
          categoryName: 'Minerals',
        },
        parent: null,
        parentIsCategory: true,
        rank: 1,
        min_measure: '',
        units: '',
        unitName: 'MG',
      },
      {
        _id: '620b461db82695d67f28e1f9',
        blendId: '1029',
        nutrientName: 'Iron',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a98a1c100bd226c13c6b',
          blendId: '40',
          categoryName: 'Minerals',
        },
        parent: null,
        parentIsCategory: true,
        rank: 2,
        min_measure: '',
        units: '',
        unitName: 'MG',
      },
      {
        _id: '620b461eb82695d67f28e1fc',
        blendId: '1030',
        nutrientName: 'Magnesium',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a98a1c100bd226c13c6b',
          blendId: '40',
          categoryName: 'Minerals',
        },
        parent: null,
        parentIsCategory: true,
        rank: 3,
        min_measure: '',
        units: '',
        unitName: 'MG',
      },
      {
        _id: '620b461eb82695d67f28e1ff',
        blendId: '1031',
        nutrientName: 'Phosphorus, P',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a98a1c100bd226c13c6b',
          blendId: '40',
          categoryName: 'Minerals',
        },
        parent: null,
        parentIsCategory: true,
        rank: 4,
        min_measure: '',
        units: '',
        unitName: 'MG',
      },
      {
        _id: '620b461fb82695d67f28e202',
        blendId: '1032',
        nutrientName: 'Potassium',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a98a1c100bd226c13c6b',
          blendId: '40',
          categoryName: 'Minerals',
        },
        parent: null,
        parentIsCategory: true,
        rank: 5,
        min_measure: '',
        units: '',
        unitName: 'MG',
      },
      {
        _id: '620b4620b82695d67f28e205',
        blendId: '1033',
        nutrientName: 'Sodium',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a98a1c100bd226c13c6b',
          blendId: '40',
          categoryName: 'Minerals',
        },
        parent: null,
        parentIsCategory: true,
        rank: 6,
        min_measure: '',
        units: '',
        unitName: 'MG',
      },
      {
        _id: '620b4620b82695d67f28e208',
        blendId: '1034',
        nutrientName: 'Zinc',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a98a1c100bd226c13c6b',
          blendId: '40',
          categoryName: 'Minerals',
        },
        parent: null,
        parentIsCategory: true,
        rank: 7,
        min_measure: '',
        units: '',
        unitName: 'MG',
      },
      {
        _id: '620b4621b82695d67f28e20b',
        blendId: '1035',
        nutrientName: 'Copper',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a98a1c100bd226c13c6b',
          blendId: '40',
          categoryName: 'Minerals',
        },
        parent: null,
        parentIsCategory: true,
        rank: 8,
        min_measure: '',
        units: '',
        unitName: 'MG',
      },
      {
        _id: '620b4622b82695d67f28e20e',
        blendId: '1036',
        nutrientName: 'Manganese',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a98a1c100bd226c13c6b',
          blendId: '40',
          categoryName: 'Minerals',
        },
        parent: null,
        parentIsCategory: true,
        rank: 9,
        min_measure: '',
        units: '',
        unitName: 'MG',
      },
      {
        _id: '620b4622b82695d67f28e211',
        blendId: '1037',
        nutrientName: 'Iodine',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a98a1c100bd226c13c6b',
          blendId: '40',
          categoryName: 'Minerals',
        },
        parent: null,
        parentIsCategory: true,
        rank: 10,
        min_measure: '',
        units: '',
        unitName: 'UG',
      },
      {
        _id: '620b4623b82695d67f28e214',
        blendId: '1038',
        nutrientName: 'Salenium',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a98a1c100bd226c13c6b',
          blendId: '40',
          categoryName: 'Minerals',
        },
        parent: null,
        parentIsCategory: true,
        rank: 11,
        min_measure: '',
        units: '',
        unitName: 'UG',
      },
      {
        _id: '620b4624b82695d67f28e217',
        blendId: '1039',
        nutrientName: 'Sulfur',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a98a1c100bd226c13c6b',
          blendId: '40',
          categoryName: 'Minerals',
        },
        parent: null,
        parentIsCategory: true,
        rank: 12,
        min_measure: '',
        units: '',
        unitName: 'MG',
      },
      {
        _id: '620b4624b82695d67f28e21a',
        blendId: '1040',
        nutrientName: 'Nickel',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a98a1c100bd226c13c6b',
          blendId: '40',
          categoryName: 'Minerals',
        },
        parent: null,
        parentIsCategory: true,
        rank: 13,
        min_measure: '',
        units: '',
        unitName: 'UG',
      },
      {
        _id: '620b4625b82695d67f28e21d',
        blendId: '1041',
        nutrientName: 'Molybdenum',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a98a1c100bd226c13c6b',
          blendId: '40',
          categoryName: 'Minerals',
        },
        parent: null,
        parentIsCategory: true,
        rank: 14,
        min_measure: '',
        units: '',
        unitName: 'UG',
      },
      {
        _id: '620b4625b82695d67f28e220',
        blendId: '1042',
        nutrientName: 'Cobalt',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a98a1c100bd226c13c6b',
          blendId: '40',
          categoryName: 'Minerals',
        },
        parent: null,
        parentIsCategory: true,
        rank: 15,
        min_measure: '',
        units: '',
        unitName: 'UG',
      },
      {
        _id: '620b4626b82695d67f28e223',
        blendId: '1043',
        nutrientName: 'Boron',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a98a1c100bd226c13c6b',
          blendId: '40',
          categoryName: 'Minerals',
        },
        parent: null,
        parentIsCategory: true,
        rank: 16,
        min_measure: '',
        units: '',
        unitName: 'UG',
      },
      {
        _id: '620b4627b82695d67f28e226',
        blendId: '1044',
        nutrientName: 'Fluoride',
        altName: null,
        status: 'Active',
        category: {
          _id: '6203a98a1c100bd226c13c6b',
          blendId: '40',
          categoryName: 'Minerals',
        },
        parent: null,
        parentIsCategory: true,
        rank: 17,
        min_measure: '',
        units: '',
        unitName: 'UG',
      },
      {
        _id: '620f89fed5a10034a84dd7e9',
        blendId: null,
        nutrientName: 'Energy',
        altName: '',
        status: 'Review',
        category: null,
        parent: null,
        parentIsCategory: false,
        rank: 300,
        min_measure: '',
        units: '',
        unitName: 'KCAL',
      },
    ],
  },
};
